title: Elizabeth North
author: Elizabeth North
email: enorth@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
 Elizabeth North is a Data Science Consultant currently based in Brussels, Belgium. 
 She specializes in machine learning algorithms with an emphasis on NLP methods.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  northelizabeth # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
